base_images:
  cli:
    name: "4.18"
    namespace: ocp
    tag: cli
build_root:
  from_repository: true
images:
- dockerfile_literal: |
    FROM this-is-ignored
    RUN dnf install -y git
    COPY . .
  from: cli
  inputs:
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/openshift-kni/commatrix/
  optional: true
  to: cli-with-git
releases:
  initial:
    integration:
      name: "4.18"
      namespace: ocp
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.18"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit-test
  commands: make test
  container:
    from: src
- as: lint
  commands: make lint
  container:
    from: src
- as: commatrix-krew-command
  steps:
    cluster_profile: aws-telco
    env:
      BASE_DOMAIN: telco5g-ci.devcluster.openshift.com
    test:
    - as: commatrix-krew-command
      commands: |
        # Install krew
        OS="$(uname | tr '[:upper:]' '[:lower:]')"
        ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/' -e 's/armv7l/arm/')"
        KREW="krew-${OS}_${ARCH}"

        mkdir -p /tmp
        curl -fsSL "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" -o /tmp/${KREW}.tar.gz
        mkdir -p /tmp/krew
        tar -xvzf /tmp/${KREW}.tar.gz -C /tmp/krew

        /tmp/krew/${KREW} install krew
        export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

        # Install the commatrix krew plugin
        oc krew install --manifest=/commatrix/cmd/commatrix-krew.yaml

        # Run the generate command and check if it worked
        echo "Running: oc commatrix generate"
        mkdir -p ${ARTIFACT_DIR}/communication-matrix
        oc commatrix generate --destDir ${ARTIFACT_DIR}/communication-matrix
        echo "SUCCESS: oc commatrix generate ran successfully!"
      from: cli-with-git
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: ipi-aws
- as: commatrix-e2e-tests
  steps:
    cluster_profile: aws-telco
    env:
      BASE_DOMAIN: telco5g-ci.devcluster.openshift.com
      USER_TAGS: |
        ci-job-source prowci
        ci-job-branch main
        ci-job-fullname openshift-kni-commatrix-e2e-tests-main
        ci-job-type commatrix-e2e-tests
        ci-repo-name commatrix
        ci-org-name openshift-kni
    test:
    - as: commatrix-e2e-tests
      commands: go mod vendor && make e2e-test
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    - ref: openshift-e2e-test
    workflow: openshift-e2e-aws-ovn-serial
- as: security
  optional: true
  steps:
    env:
      PROJECT_NAME: commatrix
      SNYK_CODE_ADDITIONAL_ARGS: --severity-threshold=high --policy-path=.snyk
    workflow: openshift-ci-security
zz_generated_metadata:
  branch: main
  org: openshift-kni
  repo: commatrix
