build_root:
  from_repository: true
releases:
  initial:
    integration:
      name: "4.17"
      namespace: ocp
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.17"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit-test
  commands: make test
  container:
    from: src
- as: lint
  commands: make lint
  container:
    from: src
- as: e2e-aws-commatrix-run
  steps:
    cluster_profile: aws-telco
    env:
      BASE_DOMAIN: telco5g-ci.devcluster.openshift.com
      USER_TAGS: |
        ci-job-source prowci
        ci-job-branch master
        ci-job-fullname openshift-kni-commatrix-e2e-aws-commatrix-run-master
        ci-job-type e2e-aws-commatrix-run
        ci-repo-name commatrix
        ci-org-name openshift-kni
    test:
    - as: e2e-aws-commatrix-run
      commands: |
        go mod vendor
        make e2e-test 
        # Download the OpenShift origin repository as a tar file
        wget https://github.com/openshift/origin/archive/refs/heads/master.tar.gz -O origin.tar.gz
        # Extract the tarball
        tar -xzf origin.tar.gz
        # Move into the extracted directory
        cd origin-master
        # Build the project
        make build
        # Run all tests using openshift-tests
        ./openshift-tests run all
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: openshift-e2e-aws-ovn
- as: security
  optional: true
  steps:
    env:
      PROJECT_NAME: commatrix
      SNYK_CODE_ADDITIONAL_ARGS: --severity-threshold=high --policy-path=.snyk
    workflow: openshift-ci-security
zz_generated_metadata:
  branch: main
  org: openshift-kni
  repo: commatrix
