build_root:
  from_repository: true
releases:
  initial:
    integration:
      name: "4.17"
      namespace: ocp
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.17"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit-test
  commands: make test
  container:
    from: src
- as: lint
  commands: make lint
  container:
    from: src
- as: e2e-aws-commatrix-run
  steps:
    cluster_profile: aws-telco
    env:
      BASE_DOMAIN: telco5g-ci.devcluster.openshift.com
      USER_TAGS: |
        ci-job-source prowci
        ci-job-branch master
        ci-job-fullname openshift-kni-commatrix-e2e-aws-commatrix-run-master
        ci-job-type e2e-aws-commatrix-run
        ci-repo-name commatrix
        ci-org-name openshift-kni
    test:
    - as: e2e-aws-commatrix-run
      commands: |
        go mod vendor
        make e2e-test 
        # Extract openshift-tests binary from OpenShift image
        # shellcheck disable=SC1091
        source "$SHARED_DIR/main.env"
        # Set go version
        if [[ "$T5CI_VERSION" == "4.12" ]] || [[ "$T5CI_VERSION" == "4.13" ]]; then
            source $HOME/golang-1.19
        elif [[ "$T5CI_VERSION" == "4.14" ]] || [[ "$T5CI_VERSION" == "4.15" ]]; then
            source $HOME/golang-1.20
        elif [[ "$T5CI_VERSION" == "4.16" ]]; then
            source $HOME/golang-1.21.11
        else
            source $HOME/golang-1.22.4
        fi
        T5_JOB_TESTS_IMAGE=$(oc adm release info --image-for=tests "registry.ci.openshift.org/ocp/release:4.17")
        oc run test-binary-extractor --restart=Never --image "$T5_JOB_TESTS_IMAGE" --command -- sleep 3600
        oc wait --for=condition=Ready pod/test-binary-extractor --timeout=5m
        oc cp test-binary-extractor:/usr/bin/openshift-tests ./openshift-tests
        chmod +x ./openshift-tests
        oc delete pod test-binary-extractor
        # Run all OpenShift tests
        ./openshift-tests run all --provider '{"type":"baremetal"}' -o e2e.log --junit-dir junit

        # Optional: compress and upload test results
        tar -czf openshift-tests-results.tar.gz e2e.log junit/
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: openshift-e2e-aws-ovn
- as: security
  optional: true
  steps:
    env:
      PROJECT_NAME: commatrix
      SNYK_CODE_ADDITIONAL_ARGS: --severity-threshold=high --policy-path=.snyk
    workflow: openshift-ci-security
zz_generated_metadata:
  branch: main
  org: openshift-kni
  repo: commatrix
